# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ab6259c394532b8b24e99b5ac352dd6c51728f430003bb684c8dfce4f8e7e10906aee22227bebef77cff9661c997f5e557083d258bca65651fbbe8dd452e6429

test:
  secret_key_base: af3f6dfb2ee1a2f954ddb8a8cd2c94397439c5c06c56f951005255dc8e79e588c0e106cd10c13f513ff6c37f81e6d7ccf26929149a9b46a2e762d14deb1f6f22

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
